<?php
	require_once "inc/sql.php";
	connect_valid();

	IF($_GET[CID]!="")
	{
		$QUERY_STRING="SELECT * FROM DISTRICT_LIST WHERE CITY_ID='".$_GET[CID]."'";
		$NO_OF_DATA=MYSQL_NUM_ROWS($RESULT=MYSQL_QUERY($QUERY_STRING));
		ECHO "<SELECT ID='DISTID' STYLE='WIDTH:120;FONT-SIZE:16' ONCHANGE=setVillageList()><OPTION VALUE=0>請選擇</OPTION>";
		FOR($SEED=0;$SEED<$NO_OF_DATA;$SEED++)
		{
			$DATA=MYSQL_FETCH_ARRAY($RESULT);
			ECHO "<OPTION VALUE='".$DATA[district_id]."'>".$DATA[district_name]."</OPTION>";
		}
		ECHO "</SELECT>";
	}
	ELSE IF($_GET[DISTID]!="")
	{
		$QUERY_STRING="SELECT * FROM VILLAGE_LIST WHERE DISTRICT_ID='".$_GET[DISTID]."'";
		$NO_OF_DATA=MYSQL_NUM_ROWS($RESULT=MYSQL_QUERY($QUERY_STRING));
		ECHO "<SELECT ID='VILLAGEID' STYLE='WIDTH:120;FONT-SIZE:16' ONCHANGE=setFormData()><OPTION VALUE=0>請選擇</OPTION>";
		FOR($SEED=0;$SEED<$NO_OF_DATA;$SEED++)
		{
			$DATA=MYSQL_FETCH_ARRAY($RESULT);
			ECHO "<OPTION VALUE='".$DATA[village_id]."'>".$DATA[village_name]."</OPTION>";
		}
		ECHO "</SELECT>";
	}

php?>